Fix map::at() const issue, by making RingBuffer operator+/- const
hideakitai/ArxContainer pull request #2
Opened 2021-12-09 22:12 UTC by brewmanz

adding following code end of setup() iin map.ino
```
    const auto& mp_ro = mp;   
    Serial.print("const map one   = ");
    Serial.println(mp_ro.at("one"));
```
results in horrible warnings like
```
     In file included from /home/xxxx/git/Arduino_ArxContainer/examples/map/map.ino:1:0:
/home/xxxx/git/yyyy/libraries/ArxContainer/ArxContainer.h: In instantiation of 'arx::map<Key, T, N>::const_iterator arx::map<Key, T, N>::find(const Key&) const [with Key = String; T = int; unsigned int N = 16; arx::map<Key, T, N>::const_iterator = const arx::RingBuffer<arx::pair<String, int>, 16>::Iterator]':
/home/xxxx/git/yyyy/libraries/ArxContainer/ArxContainer.h:709:20:   required from 'const T& arx::map<Key, T, N>::at(const Key&) const [with Key = String; T = int; unsigned int N = 16]'
/home/xxxx/git/Arduino_ArxContainer/examples/map/map.ino:50:34:   required from here
/home/xxxx/git/yyyy/libraries/ArxContainer/ArxContainer.h:659:47: warning: passing 'arx::RingBuffer<arx::pair<String, int>, 16>::const_iterator {aka const arx::RingBuffer<arx::pair<String, int>, 16>::Iterator}' as 'this' argument discards qualifiers [-fpermissive]
             const_iterator it = this->begin() + i;
/home/xxxx/git/yyyy/libraries/ArxContainer/ArxContainer.h:103:18: note:   in call to 'arx::RingBuffer<T, N>::Iterator arx::RingBuffer<T, N>::Iterator::operator+(int) [with T = arx::pair<String, int>; unsigned int N = 16]'
         Iterator operator+(const int n) {
                  ^~~~~~~~
```
This is because map's `const T& at(const Key& key) const`  is using `find(key)` which is `const_iterator find(const Key& key) const` but that uses `this->begin() + i` which is NOT `const`. 
So I have made `RingBuffer::Iterator operator+` (and `operator-`) into `const` functions.
Note that the baudrate changes to `map.ino` are for my El Cheapo nano clones which won't work above 38K4. Those lines can be discarded.

2022-01-02 07:30 UTC, hideakitai commented
Adding `const` is a good idea, but I think the latest version (v0.4.0) works fine with your additional code. I've tested the following code with Arduino Uno.

```cpp
#include <ArxContainer.h>

// initialize with initializer_list
arx::map<String, int> mp {{"one", 1}, {"two", 2}, {"four", 4}};

void setup() {
    Serial.begin(115200);
    delay(2000);

    // add contents
    mp.insert("three", 3);
    mp["five"] = 5;

    // range based access
    Serial.print({"{ "});
    for (const auto& m : mp) {
        Serial.print("{");
        Serial.print(m.first);
        Serial.print(",");
        Serial.print(m.second);
        Serial.print("},");
    }
    Serial.println({" }"});

    // key access
    Serial.print("one   = ");
    Serial.println(mp["one"]);
    Serial.print("two   = ");
    Serial.println(mp["two"]);
    Serial.print("three = ");
    Serial.println(mp["three"]);
    Serial.print("four  = ");
    Serial.println(mp["four"]);
    Serial.print("five  = ");
    Serial.println(mp["five"]);

    const auto& mp_ro = mp;
    Serial.print("const map one   = ");
    Serial.println(mp_ro.at("one"));
}

void loop() {
}
```

2022-01-02 07:35 UTC, hideakitai commented
It's excellent to merge this PR if you remove the changes in examples!

2022-01-02 07:39 UTC, hideakitai requested changes
In the latest version (v0.4.0), `map.ino` works fine with several AVR boards. So, could you remove the changes in the example?

2022-01-02 22:09 UTC, brewmanz commented
Unnecessary 'local mods' have now been removed

2022-01-03 10:59 UTC, hideakitai approved these changes

2022-01-03 10:59 UTC, merged